"""Single source of truth for country codes, names, aliases, and location hints.

This reference used to exist as four partial copies -- one in
`pipeline/normalize`, one in the LinkedIn collector, one in the Bright Data
adapter, and one in the email parser -- so a city known to one path was
invisible to another. It lives in `domain/` because it is reference data with
no infrastructure dependency.
"""

from __future__ import annotations

COUNTRY_DISPLAY_NAMES: dict[str, str] = {
    "AE": "United Arab Emirates",
    "AT": "Austria",
    "AU": "Australia",
    "BE": "Belgium",
    "CA": "Canada",
    "CH": "Switzerland",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "FR": "France",
    "GB": "United Kingdom",
    "HK": "Hong Kong",
    "IE": "Ireland",
    "IN": "India",
    "IT": "Italy",
    "LU": "Luxembourg",
    "NL": "Netherlands",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SE": "Sweden",
    "SG": "Singapore",
    "US": "United States",
    "VN": "Vietnam",
}

COUNTRY_ALIASES: dict[str, set[str]] = {
    "AE": {
        "ae",
        "uae",
        "united arab emirates",
        "vereinigte arabische emirate",
    },
    "AT": {
        "at",
        "austria",
        "osterreich",
    },
    "AU": {
        "au",
        "australia",
        "australien",
    },
    "BE": {
        "be",
        "belgie",
        "belgien",
        "belgique",
        "belgium",
    },
    "CH": {
        "ch",
        "schweiz",
        "suisse",
        "switzerland",
    },
    "CZ": {
        "cz",
        "czech republic",
        "czechia",
        "tschechien",
    },
    "DE": {
        "de",
        "deutschland",
        "germany",
    },
    "DK": {
        "danemark",
        "danmark",
        "denmark",
        "dk",
    },
    "FR": {
        "fr",
        "france",
        "frankreich",
    },
    "GB": {
        "england",
        "gb",
        "great britain",
        "uk",
        "united kingdom",
    },
    "HK": {
        "hk",
        "hong kong",
        "hongkong",
    },
    "IE": {
        "ie",
        "ireland",
        "irland",
    },
    "IN": {
        "in",
        "india",
        "indien",
    },
    "IT": {
        "it",
        "italien",
        "italy",
    },
    "LU": {
        "lu",
        "luxembourg",
        "luxemburg",
    },
    "NL": {
        "holland",
        "nederland",
        "netherlands",
        "niederlande",
        "nl",
    },
    "PL": {
        "pl",
        "poland",
        "polen",
    },
    "SE": {
        "schweden",
        "se",
        "sverige",
        "sweden",
    },
    "SG": {
        "sg",
        "singapore",
        "singapur",
    },
    "US": {
        "united states",
        "united states of america",
        "us",
        "usa",
    },
}

COUNTRY_LOCATION_HINTS: dict[str, set[str]] = {
    "AE": {
        "abu dhabi",
        "dubai",
        "uae",
        "united arab emirates",
    },
    "AT": {
        "austria",
        "graz",
        "innsbruck",
        "linz",
        "osterreich",
        "salzburg",
        "vienna",
        "wien",
        "österreich",
    },
    "AU": {
        "australia",
        "australien",
        "melbourne",
        "sydney",
    },
    "BE": {
        "antwerp",
        "antwerpen",
        "belgie",
        "belgien",
        "belgique",
        "belgium",
        "brussels",
        "bruxelles",
        "gent",
        "ghent",
        "leuven",
        "liege",
        "louvain",
    },
    "CH": {
        "basel",
        "bern",
        "geneva",
        "genf",
        "schweiz",
        "suisse",
        "switzerland",
        "zurich",
        "zürich",
    },
    "CZ": {
        "brno",
        "czech republic",
        "czechia",
        "prague",
        "praha",
        "tschechien",
    },
    "DE": {
        "aachen",
        "augsburg",
        "baden wurttemberg",
        "bavaria",
        "berlin",
        "bonn",
        "brandenburg",
        "bremen",
        "chemnitz",
        "cologne",
        "darmstadt",
        "deutschland",
        "dortmund",
        "dresden",
        "dusseldorf",
        "erfurt",
        "essen",
        "frankfurt",
        "freiburg",
        "germany",
        "gottingen",
        "hamburg",
        "hannover",
        "hanover",
        "heidelberg",
        "heilbronn",
        "hesse",
        "karlsruhe",
        "kassel",
        "kiel",
        "koblenz",
        "koln",
        "köln",
        "leipzig",
        "leverkusen",
        "lower saxony",
        "lubeck",
        "ludwigshafen",
        "magdeburg",
        "mainz",
        "mannheim",
        "mecklenburg vorpommern",
        "muenchen",
        "munchen",
        "munich",
        "munster",
        "münchen",
        "nordrhein westfalen",
        "north rhine westphalia",
        "nuernberg",
        "nuremberg",
        "offenbach",
        "osnabruck",
        "potsdam",
        "remote germany",
        "rhineland palatinate",
        "saarbrucken",
        "saarland",
        "saxony",
        "saxony anhalt",
        "schleswig holstein",
        "stuttgart",
        "thuringia",
        "ulm",
        "wiesbaden",
        "wuppertal",
        "wurzburg",
    },
    "DK": {
        "aalborg",
        "aarhus",
        "copenhagen",
        "danemark",
        "danmark",
        "denmark",
        "kobenhavn",
        "odense",
    },
    "FR": {
        "france",
        "frankreich",
        "lille",
        "lyon",
        "metz",
        "nancy",
        "paris",
        "strasbourg",
    },
    "GB": {
        "england",
        "great britain",
        "london",
        "uk",
        "united kingdom",
    },
    "HK": {
        "hong kong",
        "hongkong",
    },
    "IE": {
        "cork",
        "dublin",
        "galway",
        "ireland",
        "irland",
        "limerick",
        "waterford",
    },
    "IN": {
        "gurgaon",
        "gurugram",
        "india",
        "indien",
    },
    "IT": {
        "florence",
        "italien",
        "italy",
        "milan",
        "rome",
    },
    "LU": {
        "esch sur alzette",
        "luxembourg",
        "luxemburg",
    },
    "NL": {
        "amsterdam",
        "arnhem",
        "breda",
        "delft",
        "eindhoven",
        "groningen",
        "haarlem",
        "hague",
        "holland",
        "leiden",
        "maastricht",
        "nederland",
        "netherlands",
        "niederlande",
        "rotterdam",
        "the hague",
        "tilburg",
        "utrecht",
    },
    "PL": {
        "krakow",
        "kraków",
        "poland",
        "polen",
        "poznan",
        "poznań",
        "warsaw",
        "warszawa",
        "wroclaw",
        "wrocław",
    },
    "SE": {
        "goteborg",
        "gothenburg",
        "lund",
        "malmo",
        "stockholm",
        "sverige",
        "sweden",
        "uppsala",
    },
    "SG": {
        "singapore",
        "singapur",
    },
    "US": {
        "atlanta",
        "austin",
        "chicago",
        "new york",
        "saint louis",
        "st louis",
        "united states",
        "usa",
    },
}


def country_display_name(value: str) -> str:
    """Expand an ISO alpha-2 code; anything else is returned unchanged."""
    normalized = value.strip().upper()
    return COUNTRY_DISPLAY_NAMES.get(normalized, value.strip())
